# Generated by Django 5.2.13 on 2026-04-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('actor', 'Actor')], db_index=True, max_length=20)),
                ('canonical_signals', models.JSONField()),
                ('feature_vector', models.JSONField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.CreateModel(
            name='FingerprintReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('feedback_false_positive_count', models.IntegerField(default=0)),
                ('feedback_false_negative_count', models.IntegerField(default=0)),
                ('feedback_confirmed_count', models.IntegerField(default=0)),
                ('reputation_score', models.FloatField(default=0.0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='fingerprints.fingerprint')),
            ],
            options={
                'db_table': 'fingerprint_reputations',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('similarity', models.FloatField(default=1.0)),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_links', to='fingerprints.fingerprint')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_links', to='submissions.submission')),
            ],
            options={
                'db_table': 'submission_fingerprints',
                'indexes': [models.Index(fields=['submission', 'kind', 'is_primary'], name='submission__submiss_bf3e5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'fingerprint', 'kind'), name='uniq_submission_fingerprint_kind')],
            },
        ),
    ]
