# Generated by Django 5.2.13 on 2026-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintreputation',
            name='cluster_verdict',
            field=models.CharField(blank=True, choices=[('', '—'), ('good', 'Good'), ('bad', 'Bad')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='fingerprintreputation',
            name='cluster_verdict_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintreputation',
            name='cluster_verdict_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fingerprintreputation',
            name='cluster_verdict_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fingerprintreputation',
            name='cluster_verdict_size',
            field=models.IntegerField(default=0, help_text='Cluster size at the moment of marking'),
        ),
    ]
