# Generated by Django 5.2.13 on 2026-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0002_fingerprintreputation_cluster_verdict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintreputation',
            name='cluster_verdict',
            field=models.CharField(blank=True, choices=[('', '—'), ('good', 'Good cluster'), ('bad', 'Bad cluster'), ('not_cluster', 'Not a cluster'), ('same_user', 'Same user')], default='', max_length=16),
        ),
    ]
