# Generated by Django 5.2.13 on 2026-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=40)),
                ('hit', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('default_score', models.IntegerField(help_text='Recommended baseline deduction (typically negative).')),
                ('current_score', models.IntegerField(help_text='Customized deduction in use. Editable by investigators.')),
                ('is_implemented', models.BooleanField(db_index=True, default=False)),
                ('implementation_notes', models.TextField(blank=True, default='')),
                ('hit_count_30d', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'scoring_rules',
                'ordering': ('area', 'hit'),
                'constraints': [models.UniqueConstraint(fields=('area', 'hit'), name='uniq_scoring_rule_area_hit')],
            },
        ),
    ]
