# Generated by Django 5.2.13 on 2026-04-19 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('organizations', '0001_initial'),
        ('risk_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_profile_snapshot', models.JSONField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=253)),
                ('contact_email_raw', models.CharField(blank=True, default='', max_length=320)),
                ('contact_name_raw', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone_raw', models.CharField(blank=True, default='', max_length=40)),
                ('submitter_ip_raw', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint_raw', models.CharField(blank=True, default='', max_length=200)),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='organizations.apikey')),
                ('contact_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='entities.contactemail')),
                ('contact_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='entities.contactname')),
                ('contact_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='entities.contactphone')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='organizations.organization')),
                ('risk_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='risk_profiles.riskprofile')),
                ('submitter_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='entities.submitterip')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='DomainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('risk_score', models.IntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(blank=True, default='', max_length=20)),
                ('analyzer_version', models.CharField(blank=True, default='', max_length=20)),
                ('scan_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_result', models.JSONField()),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_scans', to='entities.registrar')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scan', to='submissions.submission')),
            ],
            options={
                'db_table': 'domain_scans',
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('deny', 'Deny'), ('review', 'Review')], db_index=True, max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('human_override_decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('deny', 'Deny'), ('review', 'Review')], default='', max_length=20)),
                ('human_override_reason', models.TextField(blank=True, default='')),
                ('human_override_by', models.CharField(blank=True, default='', max_length=200)),
                ('human_override_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='submissions.submission')),
            ],
            options={
                'db_table': 'verdicts',
            },
        ),
        migrations.CreateModel(
            name='DomainScanCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_links', to='entities.certificate')),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_links', to='submissions.domainscan')),
            ],
            options={
                'db_table': 'domain_scan_certificates',
                'constraints': [models.UniqueConstraint(fields=('domain_scan', 'certificate'), name='uniq_domain_scan_cert')],
            },
        ),
        migrations.CreateModel(
            name='DomainScanIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'A'), ('aaaa', 'AAAA'), ('mx', 'MX'), ('ns', 'NS')], max_length=10)),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_links', to='submissions.domainscan')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_links', to='entities.ipaddress')),
            ],
            options={
                'db_table': 'domain_scan_ips',
                'constraints': [models.UniqueConstraint(fields=('domain_scan', 'ip_address', 'role'), name='uniq_domain_scan_ip_role')],
            },
        ),
        migrations.CreateModel(
            name='DomainScanMXHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mx_links', to='submissions.domainscan')),
                ('mx_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_links', to='entities.mxhost')),
            ],
            options={
                'db_table': 'domain_scan_mx_hosts',
                'constraints': [models.UniqueConstraint(fields=('domain_scan', 'mx_host'), name='uniq_domain_scan_mx')],
            },
        ),
        migrations.CreateModel(
            name='DomainScanNameserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameserver_links', to='submissions.domainscan')),
                ('nameserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_links', to='entities.nameserver')),
            ],
            options={
                'db_table': 'domain_scan_nameservers',
                'constraints': [models.UniqueConstraint(fields=('domain_scan', 'nameserver'), name='uniq_domain_scan_ns')],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['organization', '-created_at'], name='submissions_organiz_69a2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['organization', 'status'], name='submissions_organiz_365efd_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['organization', 'external_ref'], name='submissions_organiz_1cce04_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['domain', '-id'], name='domain_scan_domain_4d6caf_idx'),
        ),
        migrations.AddIndex(
            model_name='domainscan',
            index=models.Index(fields=['recommendation'], name='domain_scan_recomme_9795fe_idx'),
        ),
    ]
