# Generated by Django 5.2.13 on 2026-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='review_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed — investigator agrees'), ('corrected', 'Corrected — investigator disagrees'), ('unknown', "Unknown — investigator can't tell")], db_index=True, default='', max_length=20),
        ),
    ]
