# Generated by Django 5.2.13 on 2026-04-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'db_table': 'asns',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('issuer', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('serial', models.CharField(blank=True, default='', max_length=200)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='ContactName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('full', models.CharField(max_length=200)),
                ('normalized', models.CharField(max_length=200, unique=True)),
                ('phonetic_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'contact_names',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('e164', models.CharField(max_length=20, unique=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=4)),
                ('line_type', models.CharField(blank=True, default='', max_length=20)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'contact_phones',
            },
        ),
        migrations.CreateModel(
            name='MXHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('hostname', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'db_table': 'mx_hosts',
            },
        ),
        migrations.CreateModel(
            name='Nameserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('hostname', models.CharField(max_length=253, unique=True)),
            ],
            options={
                'db_table': 'nameservers',
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('iana_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'registrars',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('normalized', models.CharField(max_length=320, unique=True)),
                ('handle', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=253)),
                ('mx_reachable', models.BooleanField(blank=True, null=True)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_role_account', models.BooleanField(default=False)),
                ('breach_count', models.IntegerField(default=0)),
                ('first_breach_at', models.DateTimeField(blank=True, null=True)),
                ('last_breach_at', models.DateTimeField(blank=True, null=True)),
                ('has_gravatar', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact_emails',
                'indexes': [models.Index(fields=['domain'], name='contact_ema_domain_ccbad0_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('hosting_provider', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='entities.asn')),
            ],
            options={
                'db_table': 'ip_addresses',
            },
        ),
        migrations.CreateModel(
            name='SubmitterIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('net_flagged_count', models.IntegerField(default=0)),
                ('net_approved_count', models.IntegerField(default=0)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter_ips', to='entities.asn')),
            ],
            options={
                'db_table': 'submitter_ips',
            },
        ),
    ]
