# Generated by Django 5.2.13 on 2026-04-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asn',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='asn',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asn',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contactname',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactname',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactname',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactname',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mxhost',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mxhost',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mxhost',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mxhost',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registrar',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registrar',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registrar',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='tag',
            field=models.CharField(blank=True, choices=[('good', 'Tagged good (strong approve pull)'), ('bad', 'Tagged bad (strong deny pull)'), ('do_not_score', 'Do not score (neutral)')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='tag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='tagged_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
