# Generated by Django 5.2.13 on 2026-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_asn_tag_asn_tag_reason_asn_tagged_at_asn_tagged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='bot_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='recent_abuse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='bot_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='recent_abuse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
