# Generated by Django 5.2.13 on 2026-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_ipaddress_bot_status_ipaddress_fraud_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='submitterip',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
