# Generated by Django 5.2.13 on 2026-04-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_ipaddress_timezone_submitterip_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_catch_all',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_deliverability',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_dns_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_domain_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_frequent_complainer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_honeypot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_leaked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_recent_abuse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_smtp_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_spam_trap_score',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_suggested_domain',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_suspect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='ipqs_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
