# Generated by Django 5.2.13 on 2026-04-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_contactemail_ipqs_catch_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='email_domain_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='email_domain_scan_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='email_domain_scan_skipped_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
