# Generated by Django 5.2.13 on 2026-04-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_as', models.CharField(choices=[('false_positive', 'False Positive — we denied something good'), ('false_negative', 'False Negative — we approved something bad'), ('confirmed', 'Confirmed — our decision was correct')], db_index=True, max_length=30)),
                ('reason_code', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('reported_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='organizations.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='organizations.organization')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='submissions.submission')),
            ],
            options={
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['organization', '-created_at'], name='feedback_organiz_fe3e6e_idx'), models.Index(fields=['submission', 'reported_as'], name='feedback_submiss_4472a6_idx')],
            },
        ),
    ]
