# Generated by Django 5.2.13 on 2026-04-20 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('organizations', '0001_initial'),
        ('submissions', '0002_verdict_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(blank=True, db_index=True, default='', help_text="For ACTION_TAG_ENTITY — e.g. 'email:42', 'ip:1.2.3.4'", max_length=255)),
                ('action', models.CharField(choices=[('verdict_confirm', 'Verdict confirmed'), ('verdict_correct', 'Verdict corrected'), ('verdict_unknown', 'Verdict unknown'), ('tag_entity', 'Entity tagged'), ('cluster_mark', 'Cluster marked'), ('threat_flag', 'Domain flagged as threat'), ('bulk_flag_threat', 'Bulk flag as threat'), ('bulk_confirm', 'Bulk confirm'), ('bulk_correct', 'Bulk correct')], db_index=True, max_length=40)),
                ('label', models.CharField(choices=[('approve', 'Approve'), ('review', 'Review'), ('deny', 'Deny'), ('bad', 'Bad (entity)'), ('good', 'Good (entity)'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('system_decision', models.CharField(blank=True, default='', max_length=20)),
                ('system_score', models.IntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('source_ui', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_labels', to='organizations.organization')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_labels', to='submissions.submission')),
            ],
            options={
                'db_table': 'training_labels',
                'indexes': [models.Index(fields=['organization', '-created_at'], name='training_la_organiz_3fffa0_idx'), models.Index(fields=['submission', 'action'], name='training_la_submiss_343b7e_idx'), models.Index(fields=['label', 'action'], name='training_la_label_50b20e_idx')],
            },
        ),
    ]
