# Generated by Django 5.2.13 on 2026-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('phishing', 'phishing'), ('malware', 'malware'), ('drainer', 'drainer'), ('scam', 'scam'), ('spam', 'spam'), ('scan', 'scan'), ('suspicious', 'suspicious')], db_index=True, max_length=20)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('brand_target', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source', models.CharField(default='', max_length=120)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], db_index=True, default='medium', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('apex_subdomain_only', models.BooleanField(default=False)),
                ('is_meta_cluster', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'threat_intel_domains',
                'indexes': [models.Index(fields=['category', 'confidence'], name='threat_inte_categor_7416d2_idx')],
            },
        ),
    ]
