# Generated by Django 5.2.13 on 2026-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('parser', models.CharField(db_index=True, help_text='Fetcher module key (e.g. plaintext_hosts, spamhaus_drop)', max_length=40)),
                ('kind', models.CharField(choices=[('domain', 'Domain/hostname'), ('ip', 'IP/CIDR'), ('url', 'URL')], default='domain', max_length=10)),
                ('default_category', models.CharField(default='scam', help_text='Default ThreatIntelDomain.category', max_length=20)),
                ('default_subcategory', models.CharField(blank=True, default='', max_length=80)),
                ('default_confidence', models.CharField(default='medium', max_length=10)),
                ('source_label', models.CharField(blank=True, default='', help_text='Human-readable source attribution', max_length=120)),
                ('refresh_interval_hours', models.IntegerField(default=24)),
                ('enabled', models.BooleanField(default=True)),
                ('api_key_env', models.CharField(blank=True, default='', max_length=80)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', help_text='ok | error | never', max_length=40)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_items_created', models.IntegerField(default=0)),
                ('last_items_updated', models.IntegerField(default=0)),
                ('last_items_skipped', models.IntegerField(default=0)),
                ('last_duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'threat_intel_feeds',
            },
        ),
    ]
