"""
eHawk-style scoring rules seed data.

Format: (area, hit, default_score, current_score, description, is_implemented)

Representative subset from the customer's eHawk configuration (2026-04-19).
`is_implemented` flags whether the pipeline has a detector that evaluates
this rule today (Phase 4 work to fill in False ones).
"""

RULES: list[tuple[str, str, int, int, str, bool]] = [

    # ---------------- EMAIL ----------------
    ("Email", "Disposable", -130, -130, "Email is disposable (e.g., 10minutemail.com)", True),
    ("Email", "Free", -10, -10, "Email from a free domain (gmail, yahoo, hotmail)", False),
    ("Email", "Role Based Email", -5, -25, "Role-based account (sales@, admin@, info@)", True),
    ("Email", "MX Record Bad", -25, -130, "Email domain MX record bad or missing", True),
    ("Email", "No Domain SPF Record", -1, -25, "No SPF record on email domain", False),
    ("Email", "Contains Many Periods", -10, -10, "Email has many periods (j.i.m.m.y@)", False),
    ("Email", "Contains Numbers", -1, -25, "Email contains numbers (peter53@)", False),
    ("Email", "Local All Numbers", -10, -10, "Email local is all numbers (123456@)", False),
    ("Email", "Accept All Mailbox", -1, -25, "Mail server accepts all emails (catch-all)", False),
    ("Email", "Undeliverable", -25, -130, "Email would bounce (SMTP probe)", False),
    ("Email", "email domain != domain", -10, -25, "Email domain differs from submitted domain", False),
    ("Email", "email domain = domain", 5, 0, "Email domain matches submitted domain (positive signal)", False),
    ("Email", "Email Local Match Name", -1, 0, "Email local matches submitted name", False),
    ("Email", "Name Not Similar", -5, -10, "Email and submitted name not similar", False),
    ("Email", "Two First Names", -5, 0, "Email local looks like two first names (JimAmy@)", False),
    ("Email", "Suspect Pattern", -5, -50, "Bot-like local pattern (asdasd@)", False),
    ("Email", "Low Quality", -1, -80, "Email local is low quality", False),
    ("Email", "Emaildomain Age 1 to 5 Days", -80, -130, "Email domain is 1-5 days old", False),
    ("Email", "Emaildomain Age 6 to 10 Days", -50, -50, "Email domain is 6-10 days old", False),
    ("Email", "Invalid", -25, -130, "Email has invalid characters (spaces etc.)", True),
    ("Email", "Empty", -25, -130, "Email is empty", True),
    ("Email", "Valid Format", 1, 0, "Proper email format (positive signal)", True),
    # IPQS Email Validation detector-backed rules
    ("Email", "IPQS Honeypot", -60, -60, "IPQS honeypot / known spam trap (wired to detector)", True),
    ("Email", "IPQS Overall Score 0 (invalid)", -50, -50, "IPQS invalid format / no DNS (wired)", True),
    ("Email", "IPQS Overall Score 1 (unreachable)", -25, -25, "IPQS DNS valid but SMTP unreachable (wired)", True),
    ("Email", "IPQS Overall Score 2 (temp reject)", -15, -15, "IPQS temporary rejection (wired)", True),
    ("Email", "IPQS Spam Trap High", -50, -50, "IPQS spam-trap score HIGH — scrub from marketing (wired)", True),
    ("Email", "IPQS Leaked/Breached", -20, -20, "Email in leaked data per IPQS (wired)", True),
    ("Email", "IPQS Recent Abuse", -30, -30, "IPQS recent abuse on email (wired)", True),
    ("Email", "IPQS Fraud Score ≥85", -40, -40, "IPQS email fraud score ≥85 (wired)", True),
    ("Email", "IPQS Frequent Complainer", -15, -15, "IPQS marks email as frequent complainer (wired)", True),

    # ---------------- DOMAIN ----------------
    ("Domain", "Age 1 to 5 Days", -80, -130, "Domain registered 1-5 days ago", True),
    ("Domain", "Age 6 to 10 Days", -50, -25, "Domain 6-10 days old", True),
    ("Domain", "Age 11 to 30 Days", -25, -10, "Domain 11-30 days old", True),
    ("Domain", "Age 31 to 40 Days", -10, -5, "Domain 31-40 days old", True),
    ("Domain", "Age 41 to 50 Days", -5, -1, "Domain 41-50 days old", True),
    ("Domain", "Blacklist", -50, -130, "Domain on a blacklist", True),
    ("Domain", "Disposable", -80, -130, "Domain is disposable email provider", True),
    ("Domain", "Expired", -50, -130, "Domain expired and not renewed", True),
    ("Domain", "Free Domain", -5, -50, "Free TLD (.tk, .ml)", False),
    ("Domain", "Parked", -25, -50, "Domain is parked, no content", True),
    ("Domain", "Parked For Sale", -50, -130, "Domain and website are for sale", True),
    ("Domain", "Phishing", -80, -130, "Domain associated with phishing activity", True),
    ("Domain", "Spam DNSBL", -50, -130, "Domain on DNS spam blacklist", True),
    ("Domain", "Suspect", -25, -130, "Domain suspect, history of issues", True),
    ("Domain", "Suspended", -80, -130, "Domain suspended by hosting provider", True),
    ("Domain", "Website: Malware or Phishing", -50, -130, "Hosting malware or phishing code", True),
    ("Domain", "Website: Default NGINX", -25, -25, "Default NGINX landing page", True),
    ("Domain", "Website: Empty Page", -25, -80, "Empty page content", True),
    ("Domain", "No Web IP", -1, -50, "Domain DNS has no IP", True),
    ("Domain", "Not Exist | No NS", -50, -130, "Nameservers not found", True),
    ("Domain", "Valid", 1, 0, "Domain format valid (positive signal)", True),

    # ---------------- IP ----------------
    ("IP", "Blacklist", -80, -130, "IP on blacklists", True),
    ("IP", "TOR Exit", -80, -80, "TOR exit node", True),
    ("IP", "Proxy - Anonymous", -80, -80, "Anonymous proxy (Hide My Ass etc.)", True),
    ("IP", "Proxy - Suspect", -50, -130, "Unconfirmed proxy suspect", True),
    ("IP", "VPN Service", -25, -25, "Known VPN service IP", True),
    ("IP", "Hosting Service", -25, -25, "AWS, Rackspace, DigitalOcean etc.", True),
    ("IP", "Connection Cable DSL", 1, 5, "Residential cable/DSL (positive signal)", False),
    ("IP", "Connection Cellular", 1, -10, "Cellular connection", False),
    ("IP", "Connection Corporate", 1, 25, "Corporate connection (positive signal)", False),
    ("IP", "Connection Type Unknown", -1, -25, "Unknown connection type", False),
    ("IP", "No Reverse PTR", -10, -25, "Missing PTR record", False),
    ("IP", "Spam Blacklist", -25, -130, "On spam IP blacklist", False),
    ("IP", "Spam History", -25, -130, "History of sending spam", False),
    ("IP", "Bots, Drone, Worm", -80, -130, "Associated with bots/worms/drones", False),
    ("IP", "Traffic Risk Level 1", -10, -80, "Some high-risk traffic from this IP", False),
    ("IP", "Traffic Risk Level 2", -25, -130, "High percentage of high-risk traffic", False),
    ("IP", "Traffic Risk Level 3", -50, -130, "Majority high-risk traffic", False),
    ("IP", "Fast Flux Networks", -50, -50, "Botnet IP used to hide fraud domains", False),
    ("IP", "Invalid IP", -10, -130, "Non-valid IPv4 or IPv6", True),
    # IPQS-detector-backed IP rules
    ("IP", "IPQS Fraud Score ≥85 (high risk)", -40, -40, "IPQS IP fraud score indicates high-risk IP (wired to detector)", True),
    ("IP", "IPQS Fraud Score 75-84 (suspicious)", -20, -20, "IPQS IP fraud score indicates suspicious IP (wired)", True),
    ("IP", "IPQS Recent Abuse", -30, -30, "IPQS flagged recent abuse events on this IP (wired)", True),
    ("IP", "IPQS Bot Activity", -40, -40, "IPQS detected bot activity (wired)", True),

    # ---------------- FINGERPRINT ----------------
    ("Fingerprint", "Fingerprint High Risk", -50, -130, "Associated with botnet or high risk", False),
    ("Fingerprint", "Invalid or Fake Fingerprint", -25, -130, "Fingerprint is invalid or fake", False),
    ("Fingerprint", "Checksum Error", -80, -130, "Fingerprint forged / fake", False),
    ("Fingerprint", "Useragent Mismatch", -25, -50, "UA and fingerprint UA differ", False),
    ("Fingerprint", "Variance Level 1", -5, -10, "IP/fingerprint timezone differ 1 hour", False),
    ("Fingerprint", "Variance Level 2", -10, -25, "Timezones differ 2 hours", False),
    ("Fingerprint", "Variance Level 3", -25, -50, "Timezones differ 3 hours", False),
    ("Fingerprint", "Variance Level 4", -50, -80, "Timezones differ 4 hours", False),
    ("Fingerprint", "Variance Level 5", -80, -130, "Timezones differ 5+ hours", False),

    # ---------------- NAME ----------------
    ("Name", "Empty", -10, 0, "Name empty or blank", True),
    ("Name", "All Lower Case", -1, 0, "All lowercase (jim smith)", False),
    ("Name", "Improper Case", -1, 0, "Mixed case (PeTer Smith)", False),
    ("Name", "First equals Last", -10, 0, "First and last identical (Jim Jim)", False),
    ("Name", "Two First Names", -5, 0, "Appears to be two first names (Jim Amy)", False),
    ("Name", "Single Character", -1, -10, "First or last is single char", False),
    ("Name", "No Vowels", -10, -5, "No vowels (cbc dfg)", False),
    ("Name", "Profanity", -50, -25, "Contains profanity", False),
    ("Name", "Invalid", -25, 0, "Invalid text blocks (Jimmmy)", False),
    ("Name", "Suspect", -10, -25, "Suspect pattern (Asd Fgh)", False),
    ("Name", "High Risk Name", -25, 0, "High-risk name (sdfsdf sdf)", False),
    ("Name", "Last Name Supicious", -5, 0, "Suspicious last name (Amy, Antonio)", False),

    # ---------------- PHONE ----------------
    ("Phone", "Empty", -10, -10, "Phone value empty", True),
    ("Phone", "Fake", -10, -10, "Phone is fake or invalid", True),
    ("Phone", "Phone shorter than required", -1, -1, "Fewer than 9 digits", True),
    ("Phone", "Area Code Issue", -25, -25, "Invalid area code", False),
    ("Phone", "Blacklist", -50, -50, "Phone on a blacklist", False),
    ("Phone", "Phone Country and Country Different", -10, -10, "Phone country ≠ submitted country", False),
    ("Phone", "Phone Country and IP Country Different", -10, -10, "Phone country ≠ IP country", False),
    ("Phone", "Toll Free", -5, -5, "Toll-free number", True),

    # ---------------- GEO-LOCATION ----------------
    ("Geo-location", "IP - Country Mismatch", -10, -10, "IP country ≠ submitted country", False),
    ("Geo-location", "Geo Region Risk", -25, -50, "IP region has fraud-activity risk", False),
    ("Geo-location", "Geo Delta 500", -5, -5, "Address/IP 500 miles apart", False),
    ("Geo-location", "Geo Delta 1,000", -10, -10, "Address/IP 1,000 miles apart", False),
    ("Geo-location", "Geo Delta 2,000", -25, -25, "Address/IP 2,000 miles apart", False),
    ("Geo-location", "Geo Delta 3,000", -25, -50, "Address/IP 3,000 miles apart", False),
    ("Geo-location", "Geo Delta 5,000+", -50, -50, "Address/IP 5,000+ miles apart", False),
    ("Geo-location", "IP Distance Velocity 500-1k", -1, -25, "IP jumped 500-1,000 miles", False),
    ("Geo-location", "IP Distance Velocity 1-2k", -5, -50, "IP jumped 1,000-2,000 miles", False),
    ("Geo-location", "IP Distance Velocity 2-3k", -10, -80, "IP jumped 2,000-3,000 miles", False),
    ("Geo-location", "IP Distance Velocity 3-4k", -25, -130, "IP jumped 3,000-4,000 miles", False),
    ("Geo-location", "IP Distance Velocity 5k+", -50, -130, "IP jumped 5,000+ miles", False),

    # ---------------- TAGS (our tagging system maps here) ----------------
    ("Tags", "IP Good", 130, 130, "This IP tagged GOOD", True),
    ("Tags", "IP Bad", -130, -130, "This IP tagged BAD", True),
    ("Tags", "Email Good", 130, 130, "This email tagged GOOD", True),
    ("Tags", "Email Bad", -130, -130, "This email tagged BAD", True),
    ("Tags", "Domain Good", 130, 130, "This domain tagged GOOD", False),
    ("Tags", "Domain Bad", -130, -130, "This domain tagged BAD", False),
    ("Tags", "Name Good", 130, 130, "This name tagged GOOD", True),
    ("Tags", "Name Bad", -130, -130, "This name tagged BAD", True),
    ("Tags", "Phone Good", 130, 130, "This phone tagged GOOD", True),
    ("Tags", "Phone Bad", -130, -130, "This phone tagged BAD", True),
    ("Tags", "Fingerprint Good", 130, 130, "This fingerprint tagged GOOD", False),
    ("Tags", "Fingerprint Bad", -130, -130, "This fingerprint tagged BAD", False),
    ("Tags", "CountryCode Tagged Good", 130, 130, "This country tagged GOOD", False),
    ("Tags", "CountryCode Tagged Bad", -130, -25, "This country tagged BAD", False),

    # ---------------- ACTIVITY REPEAT ----------------
    ("Activity Repeat", "No Repeats", 1, 5, "No repeating patterns found", False),
    ("Activity Repeat", "1 Repeat", -10, -10, "1 repeating pattern (email, IP, fingerprint, etc.)", False),
    ("Activity Repeat", "2 Repeats", -25, -10, "2 repeating patterns", False),
    ("Activity Repeat", "3 Repeats", -50, -25, "3 repeating patterns", False),
    ("Activity Repeat", "4 Repeats", -80, -50, "4 repeating patterns", False),
    ("Activity Repeat", "5+ Repeats", -80, -80, "5+ repeating patterns", False),
    ("Activity Repeat", "Lead Source or Campaign Velocity Issue", -25, -50, "Velocity from lead source exceeds threshold", False),

    # ---------------- ACTIVITY UNIQUE (cross-ref counts) ----------------
    ("Activity Unique", "IP links to 2 Emails", -1, -10, "This IP linked to 2 different emails", False),
    ("Activity Unique", "IP links to 3 Emails", -1, -10, "This IP linked to 3 different emails", False),
    ("Activity Unique", "IP links to 4 Emails", -1, -25, "This IP linked to 4 different emails", False),
    ("Activity Unique", "IP links to 5 Emails", -1, -50, "This IP linked to 5 different emails", False),
    ("Activity Unique", "IP links to 5+ Emails", -1, -80, "This IP linked to 5+ different emails", False),
    ("Activity Unique", "Email has 2 Names", -5, -10, "This email has 2 different submitted names", False),
    ("Activity Unique", "Email has 3 Names", -10, -25, "This email has 3 different submitted names", False),
    ("Activity Unique", "Email has 4 Names", -25, -50, "This email has 4 different submitted names", False),
    ("Activity Unique", "Email has 5+ Names", -80, -80, "This email has 5+ different submitted names", False),
    ("Activity Unique", "Email links to 2 IPs", -1, -5, "This email seen from 2 different IPs", False),
    ("Activity Unique", "Email links to 5+ IPs", -1, -50, "This email seen from 5+ different IPs", False),
    ("Activity Unique", "Name has 5+ Emails", -1, -80, "This name seen with 5+ different emails", False),

    # ---------------- COMMUNITY (feedback-driven) ----------------
    ("Community", "Blacklist IP", -50, -130, "Community-reported blacklist IP", False),
    ("Community", "Blacklist Email", -50, -130, "Community-reported blacklist email", False),
    ("Community", "Botnet IP", -80, -130, "Community-reported botnet IP", False),
    ("Community", "Fraud IP", -50, -130, "Community-reported fraud IP", False),
    ("Community", "Fraud Email", -80, -130, "Community-reported fraud email", False),
    ("Community", "Phishing IP", -50, -130, "Community-reported phishing IP", False),
    ("Community", "Phishing Domain", -80, -130, "Community-reported phishing domain", False),
    ("Community", "Spam IP", -10, -130, "Community-reported spam IP", False),
    ("Community", "Repeat Signup IP", -5, -50, "Repeat-signup reports on this IP", False),
    ("Community", "Positive Feedback IP", 1, 130, "Community positive feedback on IP", False),
    ("Community", "Positive Feedback Email", 1, 130, "Community positive feedback on email", False),
    ("Community", "Disposable Email", -130, -130, "Community-reported disposable email", True),
    ("Community", "Domain Suspended", -80, -130, "Community-reported suspended domain", False),
    ("Community", "High Velocity IP", -5, -80, "IP linked to 5+ emails in community data", False),
    ("Community", "No Emaildomain MX", -25, -130, "Email domain MX record gone (bouncing)", False),

    # ---------------- LOCATION (requires address collection) ----------------
    ("Location", "Country Blank", -10, -80, "Country field blank", False),
    ("Location", "Country Unknown", -10, -80, "Country code unknown", False),
    ("Location", "Invalid Country", -25, -130, "Country code invalid", False),
    ("Location", "City Blank", -10, -10, "City field blank (US/CA)", False),
    ("Location", "City <> Postalcode", -10, -10, "City doesn't match postal code", False),
    ("Location", "State <> Postalcode", -25, -25, "State doesn't match postal code", False),
    ("Location", "Invalid Postalcode", -5, -5, "Invalid postal code format", False),
    ("Location", "Street is Email Address", -1, -1, "Street field contains an email", False),
]
