# Generated by Django 5.2.13 on 2026-04-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('approve_max_score', models.IntegerField(default=30)),
                ('deny_min_score', models.IntegerField(default=70)),
                ('weight_overrides', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='organizations.organization')),
            ],
            options={
                'db_table': 'risk_profiles',
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uniq_risk_profile_org_name'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('organization',), name='uniq_default_risk_profile_per_org')],
            },
        ),
    ]
