# Generated by Django 5.2.13 on 2026-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='scoring_bands',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
